### ISSUE TITLE
how to visualize the activation maps?

### ISSUE THREAD

**Issue by DoranLyong** [zphyix/TCM#1]
Hi, thanks for sharing your nice work. 
I have read your paper and there are some questions. 

In Fig 4. you draw activation maps with Grad-CAM for each temporal frame. 
I have the experience to visualize Grad-CAM for a single image by following the repo [pytorch-grad-cam](https://github.com/jacobgil/pytorch-grad-cam). 

But, I have no idea how to apply it to temporal sequence images. Can you give me some advice? or Could I ask you can share your visualization code?

**Comment by yzfly** [comment]
Sorry for the late reply, for visual explanation for video recognition you can refer to this article:

https://medium.com/twentybn/visual-explanation-for-video-recognition-87e9ba2a675b

**Comment by QiuZhiZhe123** [comment]
> Hi, thanks for sharing your nice work. I have read your paper and there are some questions.
> 
> In Fig 4. you draw activation maps with Grad-CAM for each temporal frame. I have the experience to visualize Grad-CAM for a single image by following the repo [pytorch-grad-cam](https://github.com/jacobgil/pytorch-grad-cam).
> 
> But, I have no idea how to apply it to temporal sequence images. Can you give me some advice? or Could I ask you can share your visualization code?

Can you reproduce the accuracy of the somethingv1 dataset model? Why is my accuracy lower than the author's? Can you share the somethingv1 dataset?
